import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, CalendarDays, Check, FileText, MapPin, MessageCircleMore } from "lucide-react";
import { PublicFooter, PublicHeader } from "@/components/marketing/site-chrome";

export const metadata: Metadata = { title: "For suppliers", description: "Receive relevant product and service enquiries, review clear requirements and quote privately with Bridge-iT. Explore coverage and membership before you join." };

export default function SuppliersPage() {
  return <div className="home-v2 customer-site"><PublicHeader supplier />
    <main id="main-content">
      <section className="v2-hero v2-container customer-hero">
        <div><p className="v2-kicker">FOR THE BUSINESS BEHIND THE QUOTE</p><h1>Requests that fit.<br />A clearer way<br />to <span>quote.</span></h1><p className="v2-intro">Tell Bridge-iT what you supply, where you operate and when you have capacity. Review relevant customer requests and choose the ones worth your time.</p><div className="v2-actions"><Link className="v2-button v2-dark" href="/register">Join as a supplier <ArrowUpRight size={18} /></Link><Link className="v2-button v2-outline" href="/pricing">Compare membership plans</Link></div><p className="v2-small-note"><Check size={16} /> No introduction or winning fees.</p></div>
        <div className="supplier-workflow-card"><p className="v2-kicker">YOUR SUPPLIER WORKSPACE</p><h2>Understand the request.<br />Then decide.</h2><div><FileText size={22} /><span><b>The requirements, together</b><p>Location, timing, specification and available attachments.</p></span></div><div><MapPin size={22} /><span><b>Matched to what you do</b><p>Your products, services, coverage and capacity inform matching.</p></span></div><div><MessageCircleMore size={22} /><span><b>A private quotation</b><p>Up to five suitable suppliers can quote. No public bidding board.</p></span></div><Link className="v2-text-link" href="/demo">Explore the demonstration workspace <ArrowUpRight size={17} /></Link></div>
      </section>
      <section className="v2-how"><div className="v2-container"><div className="v2-section-head"><div><p className="v2-kicker">FROM APPLICATION TO OPPORTUNITY</p><h2>A place for your business.</h2></div></div><div className="v2-steps"><article><span>01 <FileText size={22} /></span><h3>Apply and complete your profile.</h3><p>Provide your company details, products or services, business base and contact information. Supplier approval is required before quoting.</p></article><article><span>02 <CalendarDays size={22} /></span><h3>Set your reach and availability.</h3><p>Choose appropriate membership and coverage. Keep your capabilities and lead times current so matching reflects the work you can take on.</p></article><article><span>03 <MessageCircleMore size={22} /></span><h3>Review, quote and respond.</h3><p>View matched requests in your workspace. Submit price, lead time and notes, and answer buyer questions. If selected, agree the final arrangements together.</p></article></div></div></section>
      <section className="v2-container v2-section supplier-membership"><div><p className="v2-kicker">COVERAGE THAT FITS YOUR BUSINESS</p><h2>Start close.<br />Reach further when it fits.</h2><p>Eligible service businesses can start free within 2 miles. Paid Hyperlocal, Local, Regional and Nationwide plans offer wider coverage and different live opportunity limits.</p><p>Products can be delivered further than you travel to carry out work. Configure service and delivery coverage separately within your plan.</p><Link className="v2-button v2-dark" href="/pricing">See current prices and coverage <ArrowUpRight size={17} /></Link></div><div className="public-support-card"><MapPin size={27} /><h2>Reach is eligibility.</h2><p>Being inside a coverage area does not guarantee a lead. Your category, capabilities, availability and the customer’s requirements must also match.</p><p className="public-note">Free access depends on your industry and configured coverage. A membership is not a promise of work.</p></div></section>
      <section className="v2-container v2-buyer-banner"><div><p className="v2-kicker">READY TO JOIN?</p><h2>Show us what<br />your business can do.</h2><p>Create your supplier account and complete your company profile.</p></div><Link className="v2-button v2-dark" href="/register">Apply as a supplier <ArrowUpRight size={18} /></Link></section>
    </main><PublicFooter /></div>;
}
