import { CreditCard, ShieldCheck } from "lucide-react";
import { prisma } from "@/lib/db";
import { requireSupplierPage } from "@/lib/auth/guards";
import { PortalPage, identity } from "@/components/dashboard/portal-page";
import { CheckoutButton } from "@/components/billing/checkout-button";
import { stripeConfigured } from "@/lib/stripe/server";

export const dynamic="force-dynamic";
export default async function SubscriptionPage(){const{session,companyId}=await requireSupplierPage();const company=await prisma.supplierCompany.findUniqueOrThrow({where:{id:companyId},include:{subscription:true}});const sub=company.subscription;const configured=stripeConfigured();return <PortalPage {...identity(session,company)} eyebrow="Billing" title="Subscription" description="£5 monthly membership, plus £25 only when a customer selects your quote."><div className="management-grid"><section className="panel subscription-detail"><span className="large-icon"><CreditCard size={24}/></span><p className="eyebrow">Supplier membership</p><h2>£5 / month</h2><span className={`status-pill ${sub?.status.toLowerCase()??"pending"}`}>{sub?.status??"NOT STARTED"}</span><dl><div><dt>Success fee</dt><dd>£25 per selected quote</dd></div><div><dt>Current period</dt><dd>{sub?.currentPeriodStart?.toLocaleDateString("en-GB")??"—"} – {sub?.currentPeriodEnd?.toLocaleDateString("en-GB")??"—"}</dd></div><div><dt>Renewal</dt><dd>{sub?.cancelAtPeriodEnd?"Cancels at period end":"Automatic when active"}</dd></div></dl></section><section className="panel form-section"><div className="section-heading"><div><p className="eyebrow">Billing controls</p><h2>Managed securely by Stripe</h2></div><ShieldCheck size={20}/></div><p className="body-copy">Bridge AI never stores card details. A £25 success fee becomes due only after the customer selects your price and lead time. Contact details remain locked until Stripe confirms payment.</p>{sub?.providerCustomerId?<a className="button button-dark" href="/api/billing/portal">Open billing portal</a>:configured?<CheckoutButton endpoint="/api/billing/subscription/checkout">Start £5 monthly membership</CheckoutButton>:<div className="honesty-note">Stripe is not configured in this environment, so checkout is unavailable. Add the server-only Stripe keys and membership Price ID before accepting payments.</div>}</section></div></PortalPage>}
