"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, LoaderCircle, Paperclip, Send, X } from "lucide-react";

async function responsePayload(response: Response): Promise<{ error?: string; quotationId?: string; status?: string }> {
  const body = await response.text();
  if (!body) return {};
  try { return JSON.parse(body) as { error?: string; quotationId?: string; status?: string }; }
  catch { return {}; }
}

type ExistingQuotation = {
  price: string;
  leadTimeDays: number;
  validUntil?: string;
  notes?: string;
  specification?: string;
  deliveryCost?: string;
  collectionAvailable?: boolean;
  availability?: string;
  warranty?: string;
  paymentTerms?: string;
  assumptions?: string;
  exclusions?: string;
  vatIncluded?: boolean | null;
  versionNumber?: number;
};

export function ConnectedResponse({ assignmentId, status, quotationStatus, existing }: { assignmentId: string; status: string; quotationStatus?: string; existing?: ExistingQuotation }) {
  const router=useRouter(); const [current,setCurrent]=useState(status); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function decision(decision:"accept"|"decline"){setBusy(true);setMessage("");const reason=decision==="decline"?window.prompt("Optional reason for declining")??undefined:undefined;try{const r=await fetch(`/api/assignments/${assignmentId}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,reason})});const j=await responsePayload(r);if(!r.ok)throw new Error(j.error??"The request could not be updated. Please try again.");if(!j.status)throw new Error("The request was updated, but its new status could not be confirmed.");setCurrent(j.status);router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
  async function quote(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);try{const r=await fetch("/api/quotations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignmentId,price:form.get("price"),leadTimeDays:form.get("leadTimeDays"),validUntil:form.get("validUntil")||undefined,notes:form.get("notes")||undefined,specification:form.get("specification")||undefined,deliveryCost:form.get("deliveryCost")===""?null:form.get("deliveryCost"),collectionAvailable:form.has("collectionAvailable"),availability:form.get("availability")||undefined,warranty:form.get("warranty")||undefined,paymentTerms:form.get("paymentTerms")||undefined,assumptions:form.get("assumptions")||undefined,exclusions:form.get("exclusions")||undefined,vatIncluded:form.get("vatIncluded")===""?null:form.get("vatIncluded")==="true"})});const j=await responsePayload(r);if(!r.ok)throw new Error(j.error??"The quotation could not be submitted. Please try again.");if(!j.quotationId)throw new Error("The quotation was submitted, but its reference could not be confirmed.");const file=form.get("pdf");if(file instanceof File&&file.size){const upload=new FormData();upload.set("quotationId",j.quotationId);upload.set("file",file);const ur=await fetch("/api/uploads/quotation",{method:"POST",body:upload});const uj=await responsePayload(ur);if(!ur.ok)throw new Error(uj.error??"The quotation was submitted, but the PDF could not be uploaded. Please try the PDF again.");setMessage(existing?"Quotation revised. The new PDF is queued for security scanning.":"Quotation submitted. The PDF is queued for security scanning.")}else setMessage(existing?"Quotation revision submitted successfully.":"Quotation submitted successfully.");setCurrent("QUOTED");router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Submission failed")}finally{setBusy(false)}}
  if(["PENDING","VIEWED"].includes(current))return <div><p>Accept the opportunity to unlock pricing. Declining removes it from your active queue.</p><button className="button button-dark action-primary" disabled={busy} onClick={()=>decision("accept")}>{busy?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>}Accept request</button><button className="decline-button" disabled={busy} onClick={()=>decision("decline")}><X size={15}/>Decline</button>{message&&<p className="form-result error">{message}</p>}</div>;
  if(current==="DECLINED")return <div className="decision-state"><span><X size={17}/></span><b>Request declined</b><p>Your response has been recorded.</p></div>;
  if(quotationStatus==="ACCEPTED")return <div className="decision-state success"><span><Check size={17}/></span><b>Quote selected</b><p>The customer chose your quotation to move forward. Their contact details are unlocked below. This is not yet a confirmed job.</p></div>;
  if(quotationStatus==="REJECTED"||["WITHDRAWN","EXPIRED"].includes(current))return <div className="decision-state"><span><X size={17}/></span><b>Request closed</b><p>The customer selected another quotation. This request is now read-only and cannot receive further prices.</p></div>;
  return <form className="quote-mini-form" onSubmit={quote}>{existing&&<div className="decision-state success"><span><Check size={17}/></span><b>Quotation submitted · version {existing.versionNumber??1}</b><p>You may submit a revised version while the request remains open. Earlier versions remain in the audit history.</p></div>}<label>Quote price<span className="currency-input"><i>£</i><input name="price" type="number" min="1" step="0.01" required defaultValue={existing?.price}/></span></label><label>Lead time<span className="split-input"><input name="leadTimeDays" type="number" min="1" max="730" required defaultValue={existing?.leadTimeDays}/><i>days</i></span></label><label>Valid until <small>Optional — automatically at least 7 days</small><input name="validUntil" type="date" defaultValue={existing?.validUntil}/></label><label>Specification<textarea name="specification" rows={3} maxLength={5000} defaultValue={existing?.specification}/></label><label>Delivery cost <small>Leave empty when not stated; use 0 when included</small><span className="currency-input"><i>£</i><input name="deliveryCost" type="number" min="0" step="0.01" defaultValue={existing?.deliveryCost}/></span></label><label className="toggle-row"><span><b>Collection available</b></span><input name="collectionAvailable" type="checkbox" defaultChecked={existing?.collectionAvailable}/></label><label>Availability<input name="availability" maxLength={500} defaultValue={existing?.availability} placeholder="For example: stock available now"/></label><label>Warranty<input name="warranty" maxLength={500} defaultValue={existing?.warranty}/></label><label>Payment terms<textarea name="paymentTerms" rows={2} maxLength={1000} defaultValue={existing?.paymentTerms}/></label><label>Assumptions<textarea name="assumptions" rows={3} maxLength={3000} defaultValue={existing?.assumptions}/></label><label>Exclusions<textarea name="exclusions" rows={3} maxLength={3000} defaultValue={existing?.exclusions}/></label><label>VAT<select name="vatIncluded" defaultValue={existing?.vatIncluded===true?"true":existing?.vatIncluded===false?"false":""}><option value="">Not stated</option><option value="true">Included</option><option value="false">Excluded</option></select></label><label>Notes<textarea name="notes" rows={4} maxLength={5000} defaultValue={existing?.notes}/></label><label className="upload-control"><Paperclip size={15}/><span><b>Quotation PDF</b><small>Optional PDF, up to 10 MB</small></span><input name="pdf" type="file" accept="application/pdf"/></label><button className="button button-dark action-primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>}{existing?"Submit revised quotation":"Submit quotation"}</button>{message&&<p className="form-result error">{message}</p>}</form>;
}
