"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, LoaderCircle, Paperclip, Send, X } from "lucide-react";

export function ConnectedResponse({ assignmentId, status, quotationId }: { assignmentId: string; status: string; quotationId?: string }) {
  const router=useRouter(); const [current,setCurrent]=useState(status); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function decision(decision:"accept"|"decline"){setBusy(true);setMessage("");const reason=decision==="decline"?window.prompt("Optional reason for declining")??undefined:undefined;try{const r=await fetch(`/api/assignments/${assignmentId}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,reason})});const j=await r.json();if(!r.ok)throw new Error(j.error);setCurrent(j.status);router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
  async function quote(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);try{const r=await fetch("/api/quotations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignmentId,price:form.get("price"),leadTimeDays:form.get("leadTimeDays"),validUntil:form.get("validUntil")||undefined,notes:form.get("notes")||undefined})});const j=await r.json();if(!r.ok)throw new Error(j.error);const file=form.get("pdf");if(file instanceof File&&file.size){const upload=new FormData();upload.set("quotationId",j.quotationId);upload.set("file",file);const ur=await fetch("/api/uploads/quotation",{method:"POST",body:upload});const uj=await ur.json();if(!ur.ok)throw new Error(uj.error);setMessage("Quotation submitted. The PDF is queued for security scanning.")}else setMessage("Quotation submitted successfully.");setCurrent("QUOTED");router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Submission failed")}finally{setBusy(false)}}
  if(["PENDING","VIEWED"].includes(current))return <div><p>Accept the opportunity to unlock pricing. Declining removes it from your active queue.</p><button className="button button-dark action-primary" disabled={busy} onClick={()=>decision("accept")}>{busy?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>}Accept request</button><button className="decline-button" disabled={busy} onClick={()=>decision("decline")}><X size={15}/>Decline</button>{message&&<p className="form-result error">{message}</p>}</div>;
  if(current==="DECLINED")return <div className="decision-state"><span><X size={17}/></span><b>Request declined</b><p>Your response has been recorded.</p></div>;
  if(current==="QUOTED")return <div className="decision-state success"><span><Check size={17}/></span><b>Quotation submitted</b><p>{message||`Quotation ${quotationId??""} is on record.`}</p></div>;
  return <form className="quote-mini-form" onSubmit={quote}><label>Quote price<span className="currency-input"><i>£</i><input name="price" type="number" min="1" step="0.01" required/></span></label><label>Lead time<span className="split-input"><input name="leadTimeDays" type="number" min="1" max="730" required/><i>days</i></span></label><label>Valid until<input name="validUntil" type="date"/></label><label>Notes<textarea name="notes" rows={4} maxLength={5000}/></label><label className="upload-control"><Paperclip size={15}/><span><b>Quotation PDF</b><small>Optional PDF, up to 10 MB</small></span><input name="pdf" type="file" accept="application/pdf"/></label><button className="button button-dark action-primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>}Submit quotation</button>{message&&<p className="form-result error">{message}</p>}</form>;
}
